---
- hosts: all 
  tasks:
    - name: Change permissions of setup script.
      file: dest=/home/ubuntu/hollowapp/deploy/appSetup/appSetup.sh mode=a+x

    - name: execute the HollowApp setup script
      shell: /home/ubuntu/hollowapp/deploy/appSetup/appSetup.sh
      args:
        chdir: /home/ubuntu/hollowapp
